### ISSUE TITLE
Change Language text not changing on language change for Chinese and Portuguese (ZH and PT)

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#220]
#### Describe the bug / expected behavior
Change Language text not changing on language change for Chinese and Portuguese (ZH and PT)

#### What are the steps to reproduce?

1. yarn start:example
2. Change Language by clicking on button on Login page to Chinese (ZH) or Portuguese (PT)

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2023-02-01 at 2 59 39 PM" src="https://user-images.githubusercontent.com/120575281/216034539-c26a5693-b64b-41e4-ba41-1de3cb417be5.png">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix
Go to Login.tsx line 32,
copy paste line 32 to 33 and 34
Change the language to 'zh' and 'pt'

**Comment by joebochill** [comment]
We should just need to add the required translations for the two new languages that we added.

**Comment by ektaghag-eaton** [comment]
This issue does not exist now in the master and dev branches. We are closing this issue.
