### ISSUE TITLE
Be more explicit about configuring routes in the docs

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-workflows#225]
#### Describe the desired feature/functionality
Be more explicit about the fact that the AuthNavigationContainer can ONLY contain routes as children (https://github.com/etn-ccis/blui-react-workflows/tree/dev/login-workflow#routing). This was unclear for some teams who were trying to wrap some of their Routes in a ContextProvider and ran into errors.

#### Additional Context (where / how would this be used)
N/A

#### Is this request related to a current issue?
![image](https://user-images.githubusercontent.com/29152776/222790524-8cc64354-597a-451b-8ca5-2e6683958bbd.png)

#### Suggested implementation details
Update the routing section of the docs to be more explicit.

**Comment by ektaghag-eaton** [comment]
Can we close this issue? Since in the new workflow, we have removed `AuthNavigationContainer` and updated our docs accordingly.
