### ISSUE TITLE
Update styles for the "resend verification code" button

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-workflows#229]
#### Describe the desired feature/functionality
Update styles for the "resend verification code" button on the `VerifyEmail` subscreen to match designs

#### Additional Context (where / how would this be used)
It should look like this:

<img width="530" alt="Screen Shot 2023-03-14 at 3 19 08 PM" src="https://user-images.githubusercontent.com/13989985/225114218-958e7bc1-34b1-420f-ba2b-2bc17c176b4f.png">

#### Suggested implementation details
This has already been done for `blui-react-native-workflows` so you can get most of the information surrounding this issue  and implementation details from the following issue and pr:
https://github.com/etn-ccis/blui-react-native-workflows/issues/157
https://github.com/etn-ccis/blui-react-native-workflows/pull/160/files

**Comment by huayunh** [comment]
Also available in BLUI-3915

**Comment by ektaghag-eaton** [comment]
Coming in Next version @brightlayer-ui/react-auth-workflow@5.0
