### ISSUE TITLE
Support multiple i18n instances

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#231]
#### Describe the desired feature/functionality
React auth workflow should support multiple i18n instances.
Currently, it only supports a single i18n instance. If we try to add another instance, it will get override.

#### Additional Context (where / how would this be used)
This is happening because it uses a global config/object to make it work.

#### Is this request related to a current issue?
One of our adopters tried to use 2 instances of i18n, but couldn't get through as one of them was getting overridden.

#### Suggested implementation details
Useful link:
https://luxiyalu.com/how-to-have-multiple-instances-of-i18next-for-component-library/

**Comment by joebochill** [comment]
Addressed in refactor
