### ISSUE TITLE
String overrides don't work with latest version of react-i18next

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-workflows#233]
#### Describe the bug / expected behavior
When trying to use the latest version of react-i18next (>= 12.1.0), overriding translation strings according to our documentation causes all of the built-in strings to appear as their key (i.e., the values aren't there).

#### What are the steps to reproduce?

1. Open the example project
2. Update react-i18next to version 12.1.0+
3. Observe that the translations are broken

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/29152776/228221007-7b3feeca-5e3f-4dac-b3fb-3ac69b0ed8b3.png)

#### Your environment information

N/A

#### Suggested fix

Not sure on this one...we will need to do some investigating of what changed in that library. A minor version update like that should not be a breaking change.

**Comment by ektaghag-eaton** [comment]
In the new workflow updated "react-i18next": "^13.0.3". The translation keys are working fine.

<img width="491" alt="Screenshot 2023-08-21 at 5 59 56 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/133877691/81d7d7d8-1dbd-4d63-a831-b5cfedd15351">
