### ISSUE TITLE
More space between EULA Checkbox and Divider

### ISSUE THREAD

**Issue by ektaghag-eaton** [etn-ccis/blui-react-workflows#298]
#### What are the steps to reproduce?

1. Go to /eula-screen-test
2. check space between checkbox and divider

#### Screenshots / Screen recording
<img width="1440" alt="eula_screen_design_issue" src="https://github.com/etn-ccis/blui-react-workflows/assets/133877691/53f5c131-c8b0-4e92-af9d-5ff8de9783c5">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by JeffGreiner-eaton** [comment]
Also need to look at BLUI-4324

**Comment by ektaghag-eaton** [comment]
BLUI-4660 and BLUI-4324

**Comment by ektaghag-eaton** [comment]
Fixed https://github.com/etn-ccis/blui-react-workflows/pull/455
