### ISSUE TITLE
Eula screen tests throws console warnings to wrap

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-react-workflows#390]
#### Describe the bug / expected behavior
While running should call onNext, when Next button clicked test this warning displays in console.

Warning: An update to EulaScreen inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

Several attempts of using await act() or just act() at step fireEvent.click(nextButton) does not clear up the warning.
```
act(() => {
            fireEvent.click(nextButton);
        })
```

#### What are the steps to reproduce?

1. Go to EulaScreen.test and run should call onNext, when Next button clicked test
2. Observe the warning

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Anything else to add?
https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning

**Comment by ektaghag-eaton** [comment]
A possible fix is to divide the current test case into 2 or focus only on the Next button functionality.

**Comment by ektaghag-eaton** [comment]
BLUI-4661
