### ISSUE TITLE
Design/style issues in auth workflow screens

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-workflows#418]
The following observations are made for BLUI-4507 and are based on the current dev branch @ [69096c8](https://github.com/etn-ccis/blui-react-workflows/commit/69096c86990b283f0bd1765ca096d6a0d24763f1). I have intentionally set my theme to be dark theme to check for lingering styles.

# 1
#414 

# 2
Screen: Login
Problem: The password field has an asterisk sign in the text field label. 
Expect: The field should not contain an asterisk since all fields in the form are required.
PR fix - https://github.com/etn-ccis/blui-react-workflows/pull/464

Joe's comment: remove the asterisk from both.

# 3

> Transferred to #420 

# 4

Transfered to #298 

# 5

> Transferred to #421

# 6
Screen: Registration-by-invitation - create new password
Problem: extra undesired margin above the first text field "password"
Expect: the distance between the divider and the "password" field should be 32px. You can refer to [docit](https://brightlayer-ui-dev.github.io/patterns/forms#mobile) for the dimensional details.
PR fix - https://github.com/etn-ccis/blui-react-workflows/pull/464

# 7

> Transferred to #422 

# 8
Screen: Forgot password - Forgot password success
Problem: Undesired new line.
![image](https://github.com/etn-ccis/blui-react-workflows/assets/8997218/09f845b4-6b86-4d99-a932-072a9dbd5ceb)
Expect: the period to be on the same line as the email address.
PR fix - https://github.com/etn-ccis/blui-react-workflows/pull/464

# 9

> Fixed in #419

# 10

Screen: change password (after logged in)
Problem: This is a thing only noticeable in dark theme. The card paper base includes a weird color gradient that makes the card extra bright.
<img width="542" alt="image" src="https://github.com/etn-ccis/blui-react-workflows/assets/8997218/55584763-a3e4-417e-a554-b3f876889a10">
Expect: No background gradient, like this:
<img width="523" alt="image" src="https://github.com/etn-ccis/blui-react-workflows/assets/8997218/e57267b9-cb09-4907-a94d-719aea9bbcbb">

I filed a bug report at https://github.com/etn-ccis/blui-react-themes/issues/82. If we cannot get Material Design 3 theme applied to the React auth workflow any time soon, I recommend doing an inline fix, like removing the elevation prop from the card.

# 11
Screen: multiple
Problem: On mobile (or screens with view port size smaller than 900px), the back and next button have a wrong padding:
<img width="467" alt="image" src="https://github.com/etn-ccis/blui-react-workflows/assets/8997218/06be16eb-a2b3-4cee-b11a-f5716030aa66">
The padding / margin around those buttons are not consistent.
Expect: 16px around the button.

**Comment by huayunh** [comment]
BLUI-4648

**Comment by ektaghag-eaton** [comment]
Mentioned issues are fixed.
