### ISSUE TITLE
Registration-by-invitation success screen has an unfinished sentence.

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-workflows#421]
## Describe the bug / expected behavior

When no email is provided, the success screen says (notice the period at the end):

> Your account has been successfully created with the email .

**Expect**: When no email is provided by the adopter, either throw an error or do not include the last part of the sentence "with the email..."

Or... perhaps think about what should really happen in this case. When someone self-navigates to an invite-only route for some reason... shouldn't we toss them back to the login screen? Give them an "invalid invitation link" error?

## What are the steps to reproduce?

1. Go to example project
2. Go to debug mode
3. go to registration-by-invitation
4. Go through the workflow, stop at the success screen
5. Observe that the Empty State sentence is not finished.

**Comment by ektaghag-eaton** [comment]
A short fix can be to Add 2 keys, one for email that is not provided and another for email provided.

**Comment by ektaghag-eaton** [comment]
BLUI-4663
