### ISSUE TITLE
Browser header and footer does not hide on mobile devices

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-react-workflows#50]
#### Describe the bug
Browser header and footer doesn't transition away on scroll on mobile devices

#### What is the expected behavior?
Whenever scrolling down a web app on ios, the mobile tab should transition away and the  content should expand to be full screen; this doesn't happen on mobile.

#### What are the steps to reproduce?
1. Open the login workflow on an iOS simulator
2. Observe browser header and footer not hiding on scroll

#### Screenshots or links to minimum reproduction example
![Simulator Screen Shot - iPhone 12 - 2021-05-26 at 13 11 46](https://user-images.githubusercontent.com/13989985/119703260-5b9c4480-be24-11eb-9a7e-0a3436375870.png)

**Comment by huayunh** [comment]
The screen height will need to be tall enough to make the collapse happen

**Comment by joebochill** [comment]
In Safari mobile, the header and footer will only collapse if the <body> tag is the element being scrolled. In our workflows, as they are right now, the card body is the scrolling element.
