### ISSUE TITLE
Error in the dialog / message box does not translate

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#510]
#### Describe the bug / expected behavior
Server side error thrown is getting displayed in dialog or message box.
If the language other than English is selected, then the error message is not translating. 

#### What are the steps to reproduce?

1. cd login-workflows
2. yarn start:example
3. Change the language other than English using Debug button
4. Throw error from login action (Uncomment this line https://github.com/etn-ccis/blui-react-workflows/blob/5270d35d2f251e3337f92f387a13d2fbf6098702/login-workflow/example/src/actions/AuthUIActions.tsx#L89)
5. Enter any valid email id and password
6. Click on login button
7. The error thrown is still in English

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2023-11-03 at 12 24 12 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/120575281/101e79ae-0f44-4a60-845f-c00817435e5d">

<img width="1773" alt="Screenshot 2023-11-03 at 12 23 10 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/120575281/5e07dc45-da7d-4354-9e51-0b090ce3c852">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment]
If the error is passed in English, we will display it in English. We are not doing dynamic real-time translations for unknown strings of text (everything we have translations for is pre-defined). If they want their error messages translated, they will need to translate their own error messages and pass them to us, e.g, `throw(t('My Custom Error Message'))`.

I think we should be able to translate the button label though if they are using the default and not overriding it.

**Comment by joebochill** [comment]
We can also translate the default message and title on our side if we are not doing that.
