### ISSUE TITLE
Include email in RegistrationUIActions.validateUserRegistrationRequest when it's available

### ISSUE THREAD

**Issue by kelseybrennan12** [etn-ccis/blui-react-workflows#529]
#### Describe the bug / expected behavior

In 3.1.1, the email was included in the call to `RegistrationUIActions.validateUserRegistrationRequest` on the verify code step of the registration workflow. In 4.0.0, it's no longer included.

#### Suggested fix

Send the email in the call to `RegistrationUIActions.validateUserRegistrationRequest` when it has been provided during registration.

**Comment by kelseybrennan12** [comment]
@ektaghag-eaton Do you have an approximate date for when the fix will be released?

**Comment by ektaghag-eaton** [comment]
Hi @kelseybrennan12, we have published @brightlayer-ui/react-auth-workflow@4.0.2.
