### ISSUE TITLE
Hardcoded dismissible Dialog button text

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#543]
#### Describe the bug / expected behavior
Hardcoded dismissible Dialog button text (Okay)

#### What are the steps to reproduce?
https://github.com/etn-ccis/blui-react-workflows/blob/cf8da61327f3d035441b22f790a56fef0aed23a9/login-workflow/src/components/Dialog/BasicDialog.tsx#L84
1. cd login-workflows
2. yarn start:example
3. Throw error from login action / Uncomment https://github.com/etn-ccis/blui-react-workflows/blob/cf8da61327f3d035441b22f790a56fef0aed23a9/login-workflow/example/src/actions/AuthUIActions.tsx#L89
4. Remove error display config in Login screen (currently it is set to use error message box) / Comment this block https://github.com/etn-ccis/blui-react-workflows/blob/cf8da61327f3d035441b22f790a56fef0aed23a9/login-workflow/example/src/screens/Login.tsx#L11
5. Click on Debug button and change the language other than English
6. Enter email and password in login page
7. Click Login button
8. See the error dialog has `Okay` button still in English

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2024-02-01 at 1 42 51 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/120575281/499171cc-0299-4f48-a438-6a26f23127a4">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix
Replace hard coded text with internationalization key for Okay

**Comment by surajeaton** [comment]
Pass the translation key from the component, which is using BasicDialog component.
Also remove hardcoded 'Okay' text from the button.

**Comment by joebochill** [comment]
Let's leave the default, since the Basic Dialog is a base component. We just need to make sure that wherever we are using it we are passing in a value for that prop that uses a key from the translation dictionary so it gets translated.
