### ISSUE TITLE
Reload EULA should not be tied to checkbox status

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-workflows#549]
#### Describe the bug / expected behavior
The EULA base screen currently determines whether to show the 'Reload' component based on the disabled state of the checkbox. The checkbox enabled/disabled status is completely unrelated to whether or not the EULA successfully loaded or not.

#### What are the steps to reproduce?

1. https://github.com/etn-ccis/blui-react-workflows/blob/dev/login-workflow/src/screens/EulaScreen/EulaScreenBase.tsx#L74

#### Suggested fix

Add a new prop to the EULAScreenBase: 
```
refreshConfig?: {
    onRefresh?: () => void;
    showRefreshButton?: boolean;
    refreshButtonLabel?: string;
}
```

#### Anything else to add?
The Retry button also has a hardcoded english label with no option to change — this needs to be fixed (see suggestion)

**Comment by ektaghag-eaton** [comment]
@priyankakmEaton  Check the implementation of RN side and add.
