### ISSUE TITLE
Eliminate WorkflowCardFinishState

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#552]
Describe the desired feature/functionality
Remove the WorkflowCardFinishState component — this is an unnecessary wrapper component that doesn't do anything useful.

Suggested implementation details
Move the EmptyState inline on the success screens

**Comment by joebochill** [comment]
Should we also update success screen to take props through `EmptyStateProps` instead?

**Comment by ektaghag-eaton** [comment]
Fixed [here](https://github.com/etn-ccis/blui-react-workflows/pull/577)
