### ISSUE TITLE
Update the type of param in complete registration action in the docs

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#554]
#### Describe the bug / expected behavior
- `completeRegistration` action has incorrect params / param types defined in the various docs
- It takes only one param as `userData` which is an `object`
- Need to update  `userData`  type to `object`  in :
    -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/migration-guide-3-4.md?plain=1#L83
    -- https://github.com/etn-ccis/blui-react-workflows/blob/bb59fa7c0d74259a81781983f10b11997010f9a1/login-workflow/docs/API.md?plain=1#L36
    -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/registration-workflow.md?plain=1#L85

- Need to remove 2 extra params `validationCode` and `validationEmail` from :
   -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/migration-guide-3-4.md?plain=1#L82
   -- https://github.com/etn-ccis/blui-react-workflows/blob/bb59fa7c0d74259a81781983f10b11997010f9a1/login-workflow/docs/API.md?plain=1#L36
   -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/registration-workflow.md?plain=1#L85
    
#### What are the steps to reproduce?
Checkout the following docs:
    -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/migration-guide-3-4.md?plain=1#L83
    -- https://github.com/etn-ccis/blui-react-workflows/blob/bb59fa7c0d74259a81781983f10b11997010f9a1/login-workflow/docs/API.md?plain=1#L36
    -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/registration-workflow.md?plain=1#L85
    
   -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/migration-guide-3-4.md?plain=1#L82
   -- https://github.com/etn-ccis/blui-react-workflows/blob/bb59fa7c0d74259a81781983f10b11997010f9a1/login-workflow/docs/API.md?plain=1#L36
   -- https://github.com/etn-ccis/blui-react-workflows/blob/e6b2390b18bd294f995c91cf549dba9135b7f4d8/login-workflow/docs/registration-workflow.md?plain=1#L85
        

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix
Update type to object

#### Anything else to add?
Found in https://github.com/etn-ccis/blui-react-native-workflows/pull/374#discussion_r1507904458

**Comment by KomalGDhere-eaton** [comment]
This issue got fixed. 
I can see for completeRegistration action , userData type updated to object. (https://github.com/etn-ccis/blui-react-workflows/blob/78a00d37118bcaf5e38288f97aabff9f01e75e7a/login-workflow/example/src/actions/RegistrationUIActions.tsx#L107)
