### ISSUE TITLE
Incorrect Readme title

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#593]
#### Describe the bug / expected behaviour
- Readme has an incorrect title as **Test React Auth Workflow** 
- https://www.npmjs.com/package/@brightlayer-ui/react-auth-workflow?activeTab=readme

#### What are the steps to reproduce?

1. [Go to...](https://www.npmjs.com/package/@brightlayer-ui/react-auth-workflow?activeTab=readme)
2. https://github.com/etn-ccis/blui-react-workflows/tree/dev/login-workflow#readme

#### Screenshots / Screen recording
![Screenshot 2024-05-15 at 3 42 58 PM (2)](https://github.com/etn-ccis/blui-react-workflows/assets/120575281/db803b26-0bdc-49cc-8c1d-df99866c0c60)

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by ektaghag-eaton** [comment]
https://github.com/etn-ccis/blui-react-workflows/pull/622
