### ISSUE TITLE
SX Style overrides do not work on full screens

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-react-workflows#599]
#### Describe the bug / expected behavior
Providing `sx` prop to a full screen component is ignored. The `sx` prop should be properly spread to the base component and applied.

#### What are the steps to reproduce?

1. Render the FullScreen login component
2. Add sx style rule to change a background color for example
3. Observe that no style changes are reflected

#### Code snippet / Link to minimum reproduction example
```
    <LoginScreen
        projectImage={<img src={EatonLogo} alt="logo" style={{ maxHeight: 80 }} />}
        header={<DebugComponent />}
        errorDisplayConfig={{
            mode: 'message-box',
            messageBoxConfig: {
                dismissible: true,
                position: 'top',
            },
        }}
        sx={{
            backgroundColor: 'orange',
            '& .MuiCardContent-root':{
                backgroundColor: 'red',
                '::-webkit-scrollbar': {
                    width: 0
                }
            }
        }}
    />
```

#### Suggested fix

Destructure the sx prop and pass it through to the Base components.

**Comment by ektaghag-eaton** [comment]
This is fixed here https://github.com/etn-ccis/blui-react-workflows/pull/619
