### ISSUE TITLE
ChangePasswordDialog - errorDisplayConfig.onClose does not work

### ISSUE THREAD

**Issue by lydiacho33** [etn-ccis/blui-react-workflows#656]
#### Describe the bug / expected behavior
When you pass in a prop `errorDisplayConfig.onClose` into the component `ChangePasswordDialog`, nothing changes. So when the error display appears and you click "Okay," the onClose does not get triggered.

#### Screenshots / Screen recording
[Screen Recording 2024-10-01 at 2.47.56 PM.mov.zip](https://github.com/user-attachments/files/17214940/Screen.Recording.2024-10-01.at.2.47.56.PM.mov.zip)

#### Code snippet / Link to minimum reproduction example
```
 <ChangePasswordDialog
                dialogDescription={t('CHANGE_PASSWORD.DESCRIPTION')}
                open={app.showChangePasswordDialog}
                onFinish={(): void => {
                    app.setShowChangePasswordDialog(false);
                    dispatch(forceLogoutUser());
                }}
                onPrevious={(): void => {
                    app.setShowChangePasswordDialog(false);
                }}
                errorDisplayConfig={{
                    onClose: (): void => {
                        app.setShowChangePasswordDialog(false);
                    },
                }}
/>
```

```
onClose: (): void => {
                        app.setShowChangePasswordDialog(false);
                    },
```

` app.setShowChangePasswordDialog(false)` is supposed to close the `ChangePasswordDialog`, but it never gets triggered.

#### Anything else to add?
Based on the sourcecode 

```
errorDisplayConfig={{
                ...errorDisplayConfig,
                onClose: hasVerifyCodeError
                    ? (): void => {
                          navigate(routeConfig.LOGIN as string);
                          errorDisplayConfig.onClose;
                      }
                    : errorDisplayConfig.onClose,
            }}
```

`errorDisplayConfig.onClose` doesn't get triggered

**Comment by manojleaton** [comment]
@surajeaton, Please verify

**Comment by joebochill** [comment]
The prop will need to get merged with our function rather than having it overwritten

**Comment by kelseybrennan12** [comment]
@surajeaton Is there a release available with the fix?

**Comment by surajeaton** [comment]
> @surajeaton Is there a release available with the fix?

@kelseybrennan12  Yes we have release alpha as of now.
Here it is https://www.npmjs.com/package/@brightlayer-ui/react-auth-workflow/v/5.0.1-alpha.0

Also, we will be release stable version shortly. You can use the above mentioned version as of now.

**Comment by travishenderson-eaton** [comment]
@surajeaton When testing in the dev portal, the alpha version does fix the bug. When can we expect that this will be released as a stable version?

**Comment by kelseybrennan12** [comment]
@surajeaton We would really like to pull in this fix to the AbleEdge Developer Portal via a stable release. Can you share any details about the timeline for that?

**Comment by surajeaton** [comment]
> @surajeaton We would really like to pull in this fix to the AbleEdge Developer Portal via a stable release. Can you share any details about the timeline for that?

We are in the process to publish a stable version. I will be released in 2 days.

**Comment by surajeaton** [comment]
@travishenderson-eaton and @kelseybrennan12 We have published the stable version https://www.npmjs.com/package/@brightlayer-ui/react-auth-workflow/v/6.0.0
