### ISSUE TITLE
Observation in drawer.tsx file

### ISSUE THREAD

**Issue by tejashrisawant-eaton** [etn-ccis/blui-react-workflows#657]
#### Describe the bug / expected behavior
In @brightlayer-ui/react-auth-workflow version 5.0.0 found observation for drawer.tsx file. Drawer component is getting called multiple times, as per the obseravation previously it was getting called only once. This affects the state values of select organization field in drawer component. When we try to update the value its getting reinitialise to default value. It is affecting the major functioanlities, as we are not able to work for other organizations data.

#### What are the steps to reproduce?

1. Go to...
2. Click on...

#### Screenshots / Screen recording

https://github.com/user-attachments/assets/981715d4-c0c8-4bd7-b90c-07416d701e24

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by shubham-eaton** [comment]
Suggested user to create a new folder and try with a fresh clone and resolved the issue. Hence closing the issue.
