### ISSUE TITLE
Would like to have it run on CodeSandbox

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-workflows#9]
#### Describe the desired behavior

It should run on CSB

#### Describe the current behavior

It doesn't. When I forked it, it first said "@pxblue/react-auth-workflow" is missing. When I added the dependency, it renders but with image assets missing.

#### Is this request related to a current issue

When this is done we can replace the links on docit with react auth workflow link

#### Additional Context

![image](https://user-images.githubusercontent.com/8997218/93723382-23918300-fb6c-11ea-83ea-7ef43a8625b9.png)

**Comment by joebochill** [comment]
The dependency should be easy to fix. I think when I first did the demo I hadn't yet published the package.

The static image assets can probably be swapped for web-based ones, though I wouldn't want to encourage people to use a reference to images in our github repo in a production application. Maybe we leave the local image asset in there and throw a big TODO comment around the web image and tell them to swap it with the local image in their project.

**Comment by huayunh** [comment]
Nah. Don't want to fight with CSB anymore.
